const artData = [
  {id:'rajasthan',location:'Rajasthan',art:'Miniature Painting',category:'Painting',region:'Western India',coords:[27.02,74.22],artists:'Mewar, Marwar and Kishangarh ateliers',description:'Intricate paintings that turn courtly life, poetry and devotion into jewel-like worlds of colour and detail.',history:'Rajput courts supported highly skilled ateliers from the 16th century, developing distinct schools in Mewar, Marwar and Kishangarh.',characteristics:'Fine brushwork, mineral pigments, gold detailing and layered narratives.',works:'Ragamala series · Bani Thani · Court scenes',image:'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?auto=format&fit=crop&w=900&q=85'},
  {id:'gond',location:'Madhya Pradesh',art:'Gond Art',category:'Tribal Art',region:'Central India',coords:[22.97,78.65],artists:'Jangarh Singh Shyam and Pardhan Gond artists',description:'A vibrant, rhythmic tradition where animals, trees and ancestral stories are built from dots and patterned lines.',history:'Pardhan Gond artists traditionally painted stories of clan deities and nature; the form entered galleries through artists such as Jangarh Singh Shyam.',characteristics:'Dotted fills, rhythmic lines, glowing colour and spirit-filled nature.',works:'Tree of Life · Birds and animals · Clan stories',image:'https://images.unsplash.com/photo-1549490349-8643362247b5?auto=format&fit=crop&w=900&q=85'},
  {id:'warli',location:'Maharashtra',art:'Warli Art',category:'Folk Art',region:'Western India',coords:[19.75,73.47],artists:'Warli Adivasi community',description:'Minimal white figures dance across earthen walls, recording harvests, weddings and the cycles of village life.',history:'Warli painting belongs to the Warli community of Maharashtra and was traditionally made by women during ceremonies on mud walls.',characteristics:'White rice-paste figures, geometric bodies, circular compositions and everyday scenes.',works:'Tarpa dance · Marriage चौक · Harvest scenes',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Warli%20painting.jpg'},
  {id:'madhubani',location:'Bihar',art:'Madhubani Art',category:'Folk Art',region:'Eastern India',coords:[26.35,86.08],artists:'Mithila women artists and contemporary collectives',description:'Dense, colourful compositions from Mithila bring gods, weddings, plants and protective symbols into a single frame.',history:'Also called Mithila painting, it was made in homes and ritual spaces before becoming an internationally recognised art form in the 20th century.',characteristics:'Double outlines, filled borders, symbolic flora and saturated natural colour.',works:'Kohbar · Krishna scenes · Aripana motifs',image:'https://images.unsplash.com/photo-1578301978018-3005759f48f7?auto=format&fit=crop&w=900&q=85'},
  {id:'pattachitra',location:'Odisha',art:'Pattachitra',category:'Classical Art',region:'Eastern India',coords:[19.8,85.82],artists:'Raghurajpur chitrakara families',description:'Devotional stories are painted on prepared cloth with a disciplined line and a palette shaped by temple traditions.',history:'Pattachitra is closely associated with the Jagannath temple in Puri; Raghurajpur remains a renowned village of hereditary painters.',characteristics:'Cloth support, strong contour, iconographic precision and natural pigments.',works:'Jagannath triad · Krishna Leela · Dasavatara',image:'https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=900&q=85'},
  {id:'kalighat',location:'West Bengal',art:'Kalighat Painting',category:'Folk Art',region:'Eastern India',coords:[22.57,88.36],artists:'Kalighat patua painters',description:'Bold brushstrokes and lively satire capture gods, city life and social change in the visual language of Kolkata.',history:'The style grew around the Kalighat temple in the 19th century as patua artists responded to a fast-changing urban audience.',characteristics:'Fluid contour, flat colour, expressive figures and sharp social observation.',works:'Babu and Bibi · Durga · Everyday Kolkata',image:'https://images.unsplash.com/photo-1547891654-e66ed7ebb968?auto=format&fit=crop&w=900&q=85'},
  {id:'kalamkari',location:'Andhra Pradesh',art:'Kalamkari',category:'Folk Art',region:'Southern India',coords:[15.83,80.35],artists:'Srikalahasti and Machilipatnam artisan families',description:'A pen, plant dyes and patient storytelling turn cotton into illustrated epics and patterned textiles.',history:'Two traditions developed in Andhra Pradesh: narrative hand drawing in Srikalahasti and block printing in Machilipatnam.',characteristics:'Hand-drawn outlines, earthy dyes, mythological narratives and textile craft.',works:'Ramayana panels · Tree of Life · Temple hangings',image:'https://images.unsplash.com/photo-1582550945154-66ea8fff25e1?auto=format&fit=crop&w=900&q=85'},
  {id:'tanjore',location:'Tamil Nadu',art:'Tanjore Painting',category:'Classical Art',region:'Southern India',coords:[10.79,79.14],artists:'Thanjavur hereditary painters',description:'Deities emerge from luminous surfaces of gold foil, raised relief and richly coloured glass or stone.',history:'Developed in the Thanjavur courtly milieu from the late 16th century, the form remains closely tied to devotional homes and temples.',characteristics:'Gold leaf, relief work, jewel-like details and frontal sacred icons.',works:'Krishna · Ganesha · Saraswati panels',image:'https://commons.wikimedia.org/wiki/Special:FilePath/Tanjore%20painting.jpg'},
  {id:'kerala',location:'Kerala',art:'Kerala Mural Painting',category:'Classical Art',region:'Southern India',coords:[10.5,76.27],artists:'Temple mural painters and Gurukulam traditions',description:'Monumental figures and expressive eyes animate temple walls with stories from Hindu epics and sacred lore.',history:'Kerala murals flourished in palaces and temples from the 14th century, with techniques preserved through teacher-student lineages.',characteristics:'Earth pigments, monumental scale, codified gestures and layered ornament.',works:'Nataraja · Gaja Lakshmi · Ramayana murals',image:'https://images.unsplash.com/photo-1564399579883-451a5d44ec08?auto=format&fit=crop&w=900&q=85'},
  {id:'kashmir',location:'Jammu & Kashmir',art:'Papier-mâché',category:'Folk Art',region:'Northern India',coords:[34.08,74.8],artists:'Srinagar naqash and papier-mâché artisans',description:'Lightweight forms become richly lacquered objects, covered in floral arabesques and the fine detail of naqashi.',history:"The craft is traditionally associated with Kashmir's court and trade histories, where paper pulp offered a versatile surface for decoration.",characteristics:'Moulded pulp, painted naqashi, lacquer, floral patterns and fine brushwork.',works:'Gulabdan vases · Decorative boxes · Harin motifs',image:'https://images.unsplash.com/photo-1577083552431-6e5fd01aa342?auto=format&fit=crop&w=900&q=85'}
];

const fallbackImage = `data:image/svg+xml;charset=UTF-8,${encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="800" height="500"><rect width="100%" height="100%" fill="#d8c4a6"/><path d="M0 420 Q180 180 350 380 T800 250 V500 H0Z" fill="#b95734" opacity=".72"/><circle cx="600" cy="150" r="80" fill="#e6ad55" opacity=".8"/><text x="40" y="100" font-family="serif" font-size="42" fill="#3a2b20">Indian Art Form</text></svg>')}`;
let activeFilter = 'All';

function imageMarkup(item, className='') { return `<img class="${className}" src="${item.image}" alt="${item.art} from ${item.location}" onerror="this.onerror=null;this.src='${fallbackImage}'">`; }
function openDetail(id) { const item=artData.find(entry=>entry.id===id); if(!item)return; const panel=document.getElementById('detail-panel'); panel.innerHTML=`<div class="detail-hero" style="background-image:url('${item.image}')"><div class="detail-title"><p>${item.region} · ${item.category}</p><h2>${item.location}</h2></div></div><div class="detail-content"><p>${item.description}</p><div class="detail-facts"><div><h3>Art form</h3><p>${item.art}</p></div><div><h3>Region</h3><p>${item.region}</p></div><div><h3>Historical context</h3><p>${item.history}</p></div><div><h3>Key artists / community</h3><p>${item.artists}</p></div><div><h3>Major characteristics</h3><p>${item.characteristics}</p></div><div><h3>Notable works / styles</h3><ul>${item.works.split(' · ').map(work=>`<li>${work}</li>`).join('')}</ul></div></div></div>`; document.getElementById('detail-overlay').classList.add('open'); document.getElementById('detail-overlay').setAttribute('aria-hidden','false'); }
function closeDetail(){document.getElementById('detail-overlay').classList.remove('open');document.getElementById('detail-overlay').setAttribute('aria-hidden','true');}
function renderStyles(){document.getElementById('style-grid').innerHTML=artData.map(item=>`<article class="style-card" tabindex="0" data-id="${item.id}">${imageMarkup(item)}<div class="style-card-body"><h3>${item.art}</h3><span class="state">${item.location}</span><p>${item.description}</p><span class="tag">${item.category}</span></div></article>`).join(''); document.querySelectorAll('.style-card').forEach(card=>{card.addEventListener('click',()=>focusItem(card.dataset.id));card.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' ')focusItem(card.dataset.id);});});}
function focusItem(id){document.getElementById('map-section').scrollIntoView({behavior:'smooth'});setTimeout(()=>openDetail(id),450);}
function updateVisibility(){document.querySelectorAll('.state-pin').forEach(pin=>{const item=artData.find(entry=>entry.id===pin.dataset.id);const match=activeFilter==='All'||item.category===activeFilter||(activeFilter==='Painting'&&item.category==='Painting');pin.hidden=!match;});}
function renderSearch(value){const query=value.trim().toLowerCase();const box=document.getElementById('search-results');if(!query){box.innerHTML='';return}const results=artData.filter(item=>`${item.location} ${item.art} ${item.artists}`.toLowerCase().includes(query)).slice(0,5);box.innerHTML=results.length?results.map(item=>`<button class="search-result" data-id="${item.id}" role="option"><strong>${item.art}</strong><small>${item.location} · ${item.artists}</small></button>`).join(''):'<p class="search-result">No matching tradition found.</p>';box.querySelectorAll('[data-id]').forEach(button=>button.addEventListener('click',()=>{focusItem(button.dataset.id);box.innerHTML='';document.getElementById('map-search').value='';}));}
renderStyles();
document.querySelectorAll('.state-pin').forEach(button=>button.addEventListener('click',()=>openDetail(button.dataset.id)));
document.querySelectorAll('.filter-button').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('.filter-button').forEach(item=>item.classList.remove('active'));button.classList.add('active');activeFilter=button.dataset.filter;updateVisibility();}));
document.getElementById('map-search').addEventListener('input',event=>renderSearch(event.target.value));
document.getElementById('nav-search').addEventListener('keydown',event=>{if(event.key==='Enter'){document.getElementById('map-section').scrollIntoView({behavior:'smooth'});document.getElementById('map-search').value=event.target.value;renderSearch(event.target.value);}});
document.querySelector('.overlay-close').addEventListener('click',closeDetail);document.getElementById('detail-overlay').addEventListener('click',event=>{if(event.target.id==='detail-overlay')closeDetail();});document.addEventListener('keydown',event=>{if(event.key==='Escape')closeDetail();});
const menuToggle=document.querySelector('.menu-toggle');const nav=document.querySelector('.site-nav');menuToggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');menuToggle.setAttribute('aria-expanded',open);});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menuToggle.setAttribute('aria-expanded','false');}));
